Ability to use a custom color palette
pfrankov/obsidian-colored-tags pull request #11
Opened 2023-10-25 17:43 UTC by HenrryEsposito

This pull request aims to implement a way for the user to manually edit the colors of the color palette used for coloring the tags.

A new input was created on the plugin's settings screen to receive the customized colors. The user should enter the hex code of the desired colors, separating each one with commas.

![image](https://github.com/pfrankov/obsidian-colored-tags/assets/52429925/f5738aba-8cb7-4d77-8733-0913404231ef)

2023-10-25 19:23 UTC, pfrankov commented
Thank you for you suggestion. I'd like to keep plugin simple, so can we hide this option (maybe more options in future) in `Advanced` toggle?

2023-10-25 19:47 UTC, HenrryEsposito commented
Hey @pfrankov !
I ended up noticing that there was an issue with my implementation. The way I set it up to ignore the palette settings and use custom colors ended up causing some bugs when the user no longer wanted to use the custom colors. I solved the problem by creating a toggle.
I hope you like how it turned out, but an advanced settings area would also be nice.

2023-10-25 19:49 UTC, HenrryEsposito commented
Custom colors disabled:
![image](https://github.com/pfrankov/obsidian-colored-tags/assets/52429925/e0dcebe0-5a95-4d15-b2b7-808ea06f1ee6)

Custom colors enabled:
![image](https://github.com/pfrankov/obsidian-colored-tags/assets/52429925/f9c0a41f-6c90-4bab-9c1a-7e866d7a1716)

2023-10-25 19:56 UTC, pfrankov commented on main.ts
> +		if(this.plugin.settings.enableCustomColors !== true) {
This is unusual condition. Maybe `if (!this.plugin.settings.enableCustomColors)` will be better?

2023-10-25 19:56 UTC, pfrankov commented on main.ts
> +		if(this.plugin.settings.enableCustomColors === true) {
Why do we need strict check here? Possible `if (this.plugin.settings.enableCustomColors)` will be enough

2023-10-25 19:56 UTC, pfrankov commented on main.ts
> +            .setName('Enable custom colors')
If it's custom it probably should go after the defaults

2023-11-03 21:55 UTC, pfrankov requested changes
Seems code doesn't work if no colors are provided. Could you please resolve all previous comments and double test the result?

2024-01-05 13:11 UTC, pfrankov commented
@HenrryEsposito thank you again for the idea! I've implemented it in https://github.com/pfrankov/obsidian-colored-tags/releases/tag/5.0.0

2024-01-05 13:11 UTC, closed without merging